name: FashionR2R
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.18
  - pip=20.3
  - pytorch=2.2.0
  - numpy=1.24.4
  - pip:
    - diffusers==0.26.1
    - gradio
    - opencv-python==4.9.0.80
    - imageio==2.34.0
    - einops==0.7.0
    - torch-fidelity==0.3.0
    - transformers==4.38.2
    - torchmetrics==0.6.0
    - kornia==0.6
    - scikit-learn==1.3.2
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - -e .
